### ISSUE TITLE
Make usage of kwargs consistent  

### ISSUE THREAD

**Issue by hageldave** [UniStuttgart-VISUS/uadapy#23]
Some of our functions have keyword arguments `**kwargs`. When exactly those are offered is inconsistent. E.g., it is used when

- there are many parameters, but some of them are optional and not as important or likely to be used. The less important parameters are put into kwargs so that the function signature is not becoming super long. 
- the functions that are called (e.g. pyplot functions) have many arguments, e.g. for styling. The arguments that the other (inner) function uses can be supplied with `**kwargs`.
- the functions that are called have `**kwargs`, and the `**kwargs` will then be passed on.

Ideally it would be desirable to use `**kwargs` for all of the above, extract the optional parameters for the uadapy function, and pass on `**kwargs` to the inner 'foreign' function.

```python
def uadapy_function(param1, **kwargs)
  optional1 = kwargs.get('optional1', default_value1)
  foreign_function(param1, **kwargs)
  ...
```
However, the forwarding of `**kwargs` is not well supported by pyplot, which will throw an exception when receiving arguments that it does not expect, i.e., arguments that are not intended to be used by pyplot but by uadapy or glasbey for example. This complicates the use of `**kwargs` and supplying optional parameters.

Therefore, we propose a guideline on how `**kwargs` should be used:

1. optional parameters of a uadapy function are **not** put into `**kwargs` but listed explicitly in the function signature.
2. optional parameters of foreign API calls can be supplied as dictionaries like so: 
```python
def uadapy_function(param1, pyplot_kwargs=dict(), glasbey_kwargs=dict()):
  pyplot_function(param1, **pyplot_kwargs)
  glasbey_function(**glasbey_kwargs)
 ```

---
_Sidenote: The uadapy API may make an optional argument of a foreign API call explicit. For example, an argument that is usually supplied via `**kwargs` to pyplot, e.g. `markersize`, can become an explicit argument of a uadapy function signature:_
```python
uadapy_function(size=5)
  plt.plot(..., markersize=size)
```
_The above is only a guideline for arguments that are not covered otherwise but which should still be possible to be specified._

**Comment by hageldave** [comment]
@marinaevers 

Alternative up for discussion:
The optional arguments for uadapy are supplied via `**kwargs` like so:
```python
def uadapy_function(param1, pyplot_kwargs=dict(), glasbey_kwargs=dict(), **kwargs):
  pyplot_function(param1, **pyplot_kwargs)
  glasbey_function(**glasbey_kwargs)
  optional1 = kwargs.get('optional1', default_value1)
```
This allows other developers to use `**kwargs` in their API and pass them to uadapy functions even though they may contain arguments that are not covered.

**Comment by marinaevers** [comment]
I don't think that all possible parameters need to be supported. For the goal of providing a simple plotting interface that is easy to use, I would argue that not every single fine-tuning parameter for creating the color map is necessary. I would go for your proposed solution in the first post but just use `**kwargs` for matplotlib additional arguments (or whatever we use in the respective function) and not support all optional parameters for all third-party libraries.
Another important point is removing the `**kwargs` parameter if it is not used.
